import "./App.css";
import React, { useState } from "react";
import { Helmet } from "react-helmet";
import { GlobalStyles } from "./theme/GlobalStyles";
import { BsMoonStarsFill } from "react-icons/bs";
import {
  AiOutlineLinkedin,
  AiOutlineFacebook,
  AiOutlineInstagram,
} from "react-icons/ai";
import devIMG from "./main_img.png";

function App() {
  const [isDark, setIsDark] = useState(true);

  const toggleTheme = () => setIsDark((prevState) => !prevState);

  const backgroundColor = isDark ? "#17182c" : "#fff";
  const textColor = isDark ? "white" : "black";

  return (
    <>
      <style>
        {`
    body {
        background-color: ${backgroundColor} ;
      }
    __text {
    color: ${textColor}
    }
    `}
      </style>
      <Helmet>
        <title>Zak - Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="../dist/output.css" rel="stylesheet" />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Encode+Sans+Expanded:wght@900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Helmet>

      <main>
        <nav className="position-fixed top-0 left-0 right-0 z-999 mb-3 p-0 flex flex-col">
          <div className="flex flex-auto flex-row items-center w-full h-12">
            <a
              href="#"
              className={`hover:text-gray-300 text-${textColor} text-xl encode-font flex-1 mt-4 ml-3`}
            >
              <span className="text-gray-400">&lt; </span>codedByZak
              <span className="text-gray-400"> /&gt;</span>
            </a>
            <ul className="inline-flex justify-center">
              <li className="ml-auto mr-10 mt-4 position-relative">
                <BsMoonStarsFill
                  onClick={toggleTheme}
                  className={`__moon-star text-${textColor}`}
                />
              </li>
              <li className="__resume align-middle ml-auto mr-4 px-4 py-2 rounded-lg h-5">
                <a className="text-white" href="#">
                  Resume
                </a>
              </li>
            </ul>
          </div>
          <hr className="mt-3 mb-3"></hr>
        </nav>

        <div className="__mainHero mt-7 text-center p-7">
          <h2 className="  text-5xl font-extrabold text-teal-600 py-2">
            Zakaria Abdessemed
          </h2>
          <h3 className={`text-2xl font-bold text-${textColor} py-5`}>
            Full Stack MERN developer
          </h3>
          <div class="typewriter">
            <p
              className={`text-md text-${textColor} whitespace-normal leading-2 py-2`}
            >
              Freelancer providing services for programming needs. Join me down
              below and let's get in work.
            </p>
          </div>
        </div>

        <div className={`flex justify-center gap-16 rounded text-${textColor}`}>
          <a href="https://www.linkedin.com/in/zakaria-abdessemed-05405725a">
            <AiOutlineLinkedin className="text-4xl hover:text-gray-300" />
          </a>
          <a href="https://www.facebook.com/profile.php?id=100009007842352">
            <AiOutlineFacebook className="text-4xl hover:text-gray-300" />
          </a>
          <a href="https://www.instagram.com/zak_u_u/">
            <AiOutlineInstagram className="text-4xl hover:text-gray-300" />
          </a>
        </div>

        <div className="mx-auto my-7 bg-gradient-to-b max-w-md from-cyan-600 rounded-full flex items-center justify-center overflow-hidden">
          <img src={devIMG} className="h-25 w-30 object-fit" alt="" />
        </div>
      </main>
    </>
  );
}

export default App;
