import React from 'react'
import { Helmet } from "react-helmet";
export default function Header() {
  return (
    <Helmet>
        <title>Zak - Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="../dist/output.css" rel="stylesheet" />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Encode+Sans+Expanded:wght@900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Helmet> 
  )
}
